apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.identity.label }}-service
  labels:
    app: {{ .Values.appGroup }}
    tier: {{ .Values.backend.general.labels.tier }}
    service: {{ .Values.backend.identity.label }}
spec:
  ports:
  - port: {{ .Values.backend.identity.ports.service }}
    protocol: TCP
    targetPort: {{ .Values.backend.identity.ports.container }}
  selector:
    app: {{ .Values.appGroup }}
    tier: {{ .Values.backend.general.labels.tier }}
    service: {{ .Values.backend.identity.label }}