appGroup: mr

environment: development

general:
  images:
    pullPolicy: Always
    repository: localhost:5000
    tag: latest
  labels:
    name: mr

backend:
  general:
    labels:
      tier: backend
  webapi:
    replicas: 2
    ports:
      container: 80
      service: 6002
    label: webapi
    image: webapi-service
  identity:
    replicas: 2
    ports:
      container: 80
      service: 6000
      external: 5000
    host:
      external: localhost
    label: identity
    image: identity-service
  storage:
    replicas: 2
    ports:
      container: 80
      service: 6004
    label: storage
    image: storage-service

frontend:
  general:
    labels:
      tier: frontend
  portal:
    replicas: 2
    ports:
      container: 80
      service: 8888
    label: portal
    image: portal
    