version: "3.7"
services:

    webapi_service:
        build:
          context: .
          dockerfile: ./AppServices/WebAPIService/Dockerfile        
        container_name: webapi_service
        restart: unless-stopped
        expose:
          - 5002
        environment: 
          API_DB_HOST: "db"
          API_DB_PORT: "5432"
          API_DB_USER: "/run/secrets/api_db_user"
          API_DB_PASSWORD: "/run/secrets/api_db_password"
          PIS_HOST: "identity_service"
          PIS_PORT: "5000"
          RMQ_USER: "/run/secrets/rabbitmq_user"
          RMQ_PASSWORD: "/run/secrets/rabbitmq_password"
          RMQ_HOST: "rabbitmq"
          RMQ_PORT: "5672"
          ASPNETCORE_ENVIRONMENT: "Development"          
          SeqURL: "http://seq:5341"
        depends_on:    
          -  identity_service  
          # -  rabbitmq  
          # -  seq
        secrets:
          - api_db_password
          - api_db_user
          - rabbitmq_password
          - rabbitmq_user
          
          
    identity_service:
        build:
          context: .
          dockerfile: ./AppServices/IdentityService/Dockerfile        
        container_name: identity_service
        restart: unless-stopped
        expose:
          - 5000
        environment: 
          PIS_DB_HOST: "db"
          PIS_DB_PORT: "5432"
          PIS_DB_USER: "/run/secrets/is_db_user"
          PIS_DB_PASSWORD: "/run/secrets/is_db_password"
          ASPNETCORE_ENVIRONMENT: "Development"
          Serilog__WriteTo__2__Args__serverUrl: "http://seq:5341"
        depends_on:
          -  db    
        secrets:
          - is_db_password
          - is_db_user


    db:
        image: postgres:11.7-alpine
        volumes: 
          - pg_data:/var/lib/postgresql/data        
        ports: 
          - 5432:5432
        container_name: db
        restart: unless-stopped
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
            POSTGRES_USER_FILE: "/run/secrets/db_user"
        secrets:
          - db_password
          - db_user

    
    # rabbitmq:
    #     build:
    #       context: ./ThirdPartyImages
    #       dockerfile: RabbitMQ
    #     container_name: rabbitmq
    #     restart: unless-stopped
    #     environment: 
    #       RABBITMQ_DEFAULT_USER: "/run/secrets/rabbitmq_user"
    #       RABBITMQ_DEFAULT_PASS: "/run/secrets/rabbitmq_password"
    #     healthcheck:
    #       test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #       interval: 30s
    #       timeout: 10s
    #       retries: 5
    #     volumes:
    #         - rmq_etc:/etc/rabbitmq/
    #         - rmq_data:/var/lib/rabbitmq/
    #         - rmq_logs:/var/log/rabbitmq/
    #     expose:
    #       - 4369
    #       - 5671
    #       - 5672
    #       - 25672
    #       - 15671
    #     ports:            
    #         - 15672:15672
    #     secrets:
    #       - rabbitmq_password
    #       - rabbitmq_user


    # notification_worker:
    #     build:
    #       context: .
    #       dockerfile: ./AppServices/WorkerServices/NotificationWorkerService/Dockerfile        
    #     container_name: notification_worker
    #     restart: unless-stopped
    #     environment: 
    #       RMQ_USER: "/run/secrets/rabbitmq_user"
    #       RMQ_PASSWORD: "/run/secrets/rabbitmq_password"
    #       RMQ_HOST: "rabbitmq"
    #       RMQ_PORT: "5672"
    #       DOTNET_ENVIRONMENT: "Development"
    #     depends_on:    
    #       -  rabbitmq  
    #     secrets:
    #       - rabbitmq_password
    #       - rabbitmq_user
          

    # seq:
    #  image: datalust/seq
    #  container_name: seq
    #  restart: unless-stopped
    #  expose: 
    #   - 5341
    #  ports:
    #   - 5340:80
    #  environment: 
    #   ACCEPT_EULA: Y
    #  volumes: 
    #   - seq_data:/data


    # prometheus:
    #   image: prom/prometheus
    #   container_name: prometheus
    #   restart: unless-stopped
    #   ports:
    #     - 9090:9090
    #   volumes:
    #     - ./ThirdPartyImages/prometheus.yml:/etc/prometheus/prometheus.yml:ro


    # grafana: 
    #   image: grafana/grafana      
    #   environment:
    #     GF_SECURITY_ADMIN_PASSWORD: "/run/secrets/grafana_password"
    #   container_name: grafana
    #   restart: unless-stopped
    #   ports:
    #     - 3000:3000
    #   volumes: 
    #     - grafana-storage:/var/lib/grafana grafana/grafana
    #     secrets:
    #       - grafana_password

    angular:
      build:
        context: .
        dockerfile: ./ClientApplications/Angular/Dockerfile        
      container_name: angular
      restart: unless-stopped
      ports:
        - 8888:80
      environment: 
        API_URI: "webapi_nginx:8989/api"
        IS_URI:  "identity_nginx:8989"
      depends_on:        
        - identity_nginx
        - webapi_nginx   


    webapi_nginx:
      build: 
        context: .
        dockerfile: ./AppServices/WebAPIService/nginx/Dockerfile
      container_name: webapi_nginx
      restart: unless-stopped
      ports:
        - 5002:8989
      depends_on: 
        - webapi_service
    

    identity_nginx:
      build: 
        context: .
        dockerfile: ./AppServices/IdentityService/nginx/Dockerfile
      container_name: identity_nginx
      restart: unless-stopped
      ports:
        - 5000:8989
      depends_on: 
        - identity_service
      
  
volumes: 
  pg_data:
  # rmq_etc:
  # rmq_data:
  # rmq_logs:
  # seq_data:
  # grafana-storage:

secrets:
  db_user:
    file: ./secrets/DB_USER
  db_password:
    file: ./secrets/GRANT_PASSWORD
  api_db_password:
    file: ./secrets/GRANT_PASSWORD
  api_db_user:
    file: ./secrets/DB_USER 
  is_db_password:
    file: ./secrets/GRANT_PASSWORD
  is_db_user:
    file: ./secrets/DB_USER 
  grafana_password:
    file: ./secrets/GRANT_PASSWORD
  rabbitmq_user:
    file: ./secrets/RABBITMQ_USER 
  rabbitmq_password:
    file: ./secrets/GRANT_PASSWORD

