// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Megarender.IdentityService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Megarender.IdentityService.CommunicationChannel", b =>
                {
                    b.Property<int>("CommunicationChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("CommunicationChannelId");

                    b.ToTable("CommunicationChannel");

                    b.HasData(
                        new
                        {
                            CommunicationChannelId = 1,
                            Value = "Phone"
                        },
                        new
                        {
                            CommunicationChannelId = 2,
                            Value = "Email"
                        },
                        new
                        {
                            CommunicationChannelId = 3,
                            Value = "Telegram"
                        });
                });

            modelBuilder.Entity("Megarender.IdentityService.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("Megarender.IdentityService.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("PreferredCommunicationChannel")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Megarender.IdentityService.User", b =>
                {
                    b.OwnsOne("Megarender.IdentityService.CommunicationChannelsData", "CommunicationChannelsData", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("TelegramId")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("CommunicationChannelsData");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("CommunicationChannelsData");
                });
#pragma warning restore 612, 618
        }
    }
}
