apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.webapi.label }}-ingress
  labels:
    app: {{ .Values.appGroup }}
    tier: {{ .Values.backend.general.labels.tier }}
    service: {{ .Values.backend.webapi.label }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "kestrel"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.backend.webapi.label }}-service
                port:
                  number: {{ .Values.backend.webapi.ports.service }}