apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.identity.label }}-deployment 
  labels:
    app: {{ .Values.appGroup }}
    tier: {{ .Values.backend.general.labels.tier }}
    service: {{ .Values.backend.identity.label }}
spec:
  replicas: {{ .Values.backend.identity.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appGroup }}
      tier: {{ .Values.backend.general.labels.tier }}
      service: {{ .Values.backend.identity.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.appGroup }}
        tier: {{ .Values.backend.general.labels.tier }}
        service: {{ .Values.backend.identity.label }}
    spec:
      containers:
        - name: {{ .Values.backend.identity.label }}
          image: {{ .Values.general.images.repository }}/{{ .Values.backend.identity.image }}:{{ .Values.general.images.tag }}
          imagePullPolicy: {{ .Values.general.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.identity.ports.container }}
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER_FILE
              value: ~/secrets/IS_DB_USER
            - name: DB_PWD_FILE
              value: ~/secrets/IS_DB_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Serilog__WriteTo__2__Args__serverUrl
              value: http://seq:5341