apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.portal.label }}-deployment 
  labels:
    app: {{ .Values.appGroup }}
    tier: {{ .Values.frontend.general.labels.tier }}
    service: {{ .Values.frontend.portal.label }}
spec:
  replicas: {{ .Values.frontend.portal.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appGroup }}
      tier: {{ .Values.frontend.general.labels.tier }}
      service: {{ .Values.frontend.portal.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.appGroup }}
        tier: {{ .Values.frontend.general.labels.tier }}
        service: {{ .Values.frontend.portal.label }}
    spec:
      containers:
        - name: {{ .Values.frontend.portal.label }}
          image: {{ .Values.general.images.repository }}/{{ .Values.frontend.portal.image }}:{{ .Values.general.images.tag }}
          imagePullPolicy: {{ .Values.general.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.portal.ports.container }}
          env:
            - name: API_URI
              value: "{{ .Release.Name }}-{{ .Values.backend.webapi.label }}-service:{{ .Values.backend.webapi.ports.container }}/api"
            - name: IS_URI
              value: "{{ .Release.Name }}-{{ .Values.backend.identity.label }}-service:{{ .Values.backend.identity.ports.container }}"
            - name: STORAGE_URI
              value: "{{ .Release.Name }}-{{ .Values.backend.storage.label }}-service:{{ .Values.backend.storage.ports.container }}"