name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v1     
            - name: Reveal secrets
              env:
                SUPER_SECRET: ${{ secrets.SuperSecret }}
              run: git secret reveal -p $SUPER_SECRET 
            - name: Build images
              run: docker-compose build
