name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Install git-secret              
              uses: Kingmidas74/git-secret-github-action@0.1.0

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true
              
            - name: Reveal secrets
              env:
                SECRETS_VERBOSE: 1              
              run: |                
                git secret reveal -p ${{ secrets.SECRET_PWD }}                
            
            - name: Build images
              run: docker-compose build
