name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Install git-secret
              env: 
                SECRETS_VERBOSE: 1
                PREFIX: "/usr/local"
              run: |   
                git clone https://github.com/sobolevn/git-secret.git git-secret
                cd git-secret
                sudo make build
                sudo make install

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true

            - name: Checkout sources
              uses: actions/checkout@v2
              
            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
                SECRETS_VERBOSE: 1              
              run: |                
                git secret tell 
                git secret reveal -p ${{ secrets.SECRET_PWD }}
            
            - name: Build images
              run: docker-compose build
