name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
                SECRET_PWD2: ${{ toJson(secrets.SECRET_PWD) }}
              run: |
                sudo apt install git-secret     
                echo ${{secrets.SECRET_PWD}} | sed 's/./& /g'    
                git secret tell kingmidas1992@gmail.com
                echo $SECRET_PWD | sed 's/./& /g'
                git secret reveal -p ${{secrets.SECRET_PWD}} -F
            - name: Build images
              run: docker-compose build
