name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: Configure GPG Key
              run: |
                mkdir -p ~/.gnupg/
                printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
                gpg --import ~/.gnupg/private.key
              env:
                GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
            - name: Checkout sources
              uses: actions/checkout@v1     
            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
              run: |
                sudo apt install git-secret 
                git secret tell kingmidas1992@gmail.com
                git secret reveal -p $SECRET_PWD 
            - name: Build images
              run: docker-compose build
