name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    tests:

        runs-on: ubuntu-latest

        steps:

            - name: Install git-secret              
              uses: Kingmidas74/git-secret-github-action@latest
            
            - name: Install dotnet
              uses: actions/setup-dotnet@v1.7.2
              with:
                dotnet-version: '5.0.x'         

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true
              
            - name: Reveal secrets         
              run: |                
                git secret reveal -p ${{ secrets.SECRET_PWD }}
            
            - name: Up containers
              run: docker-compose up -d db

            - name: Unit tests for Business Layer
              uses: zyborg/dotnet-tests-report@v1
              with:
                project_path: backend/tests/Megarender.Business.Tests/Megarender.Business.UnitTests
                report_name: unit_business_tests
                report_title: Unit Business Tests
                github_token: ${{ secrets.GITHUB_TOKEN }}
                gist_name: unit_business_tests.md
                gist_badge_label: 'Unit Tests: %Counters_passed%/%Counters_total%'
                gist_token: ${{ secrets.GIST_TOKEN }}

            - name: Integration tests for Business Layer
              uses: zyborg/dotnet-tests-report@v1
              with:
                project_path: backend/tests/Megarender.Business.Tests/Megarender.Business.IntegrationTests
                report_name: integration_business_tests
                report_title: Integration Business Tests
                github_token: ${{ secrets.GITHUB_TOKEN }}
                gist_name: integration_business_tests.md
                gist_badge_label: 'Integration Tests: %Counters_passed%/%Counters_total%'
                gist_token: ${{ secrets.GIST_TOKEN }}
            
            - name: Shutdown containers
              run: docker-compose down

    build:

        needs: tests

        runs-on: ubuntu-latest

        steps:

            - name: Install git-secret              
              uses: Kingmidas74/git-secret-github-action@latest

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true
              
            - name: Reveal secrets         
              run: |                
                git secret reveal -p ${{ secrets.SECRET_PWD }}                
            
            - name: Build images
              run: docker-compose build

