name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Setup git user
              uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true                
            
            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
              run: |
                sudo apt install git-secret              
                git config --local --get user.name
                ls -las       
                sudo chmod -R 777 ./secrets
                git config user.email "kingmidas1992@gmail.com"
                git secret tell
                git secret reveal -p ${{ secrets.SECRET_PWD }}
            
       #     - name: Decrypt GPG secrets
        #      uses: minddocdev/decrypt-action@master
         #     with:
          #      files: ./secrets/DB_USER.secret,./secrets/GRANT_PASSWORD.secret
           #     passphrase: ${{ secrets.SECRET_PWD }}
            
            - name: Build images
              run: docker-compose build
