name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true                
            
            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
              run: |
                sudo apt install git-secret              
                ls -las       
                git secret tell kingmidas1992@gmail.com       
            
            - name: Decrypt GPG secrets
              uses: minddocdev/decrypt-action@master
              with:
                files: ./secrets/DB_USER.secret,./secrets/GRANT_PASSWORD.secret
                passphrase: ${{ secrets.SECRET_PWD }}
            
            - name: Build images
              run: docker-compose build
