name: Docker Image CI

on: 
    push:
        branches:
            - master
            - develop 
    pull_request:
        branches:
            - master
            - develop 

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
                          
            - name: Install git-secret
              working-directory: ./temp
              run: |
                git clone https://github.com/sobolevn/git-secret.git git-secret
                cd git-secret && make build
                PREFIX="/usr/local" make install

            - name: Configure GPG Key
              uses: crazy-max/ghaction-import-gpg@v3
              with:
                gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                passphrase: ${{ secrets.SECRET_PWD }}
                git-user-signingkey: true
                git-commit-gpgsign: true          

            
            - name: Checkout sources
              uses: actions/checkout@v2
              
            - name: Reveal secrets
              env:
                SECRET_PWD: ${{ secrets.SECRET_PWD }}
              run: |                
                ls -las       
                sudo chmod -R 777 ./secrets
                git secret tell kingmidas1992@gmail.com                
                git secret reveal -p ${{ secrets.SECRET_PWD }}
            
       #     - name: Decrypt GPG secrets
        #      uses: minddocdev/decrypt-action@master
         #     with:
          #      files: ./secrets/DB_USER.secret,./secrets/GRANT_PASSWORD.secret
           #     passphrase: ${{ secrets.SECRET_PWD }}
            
            - name: Build images
              run: docker-compose build
