name: Docker Image CI

on: [push]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Checkout sources          
        - run: docker-compose build
        - name: Build images
