name: Docker Image CI

on: [push]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v1        
            - name: Build images
              run: docker-compose build
